### ISSUE TITLE
请问如何使用快键键win+E自动打开这个软件？

### ISSUE THREAD

**Issue by ganpanlin** [MMengyiyu/XYplorer_Help#1]
请问如何使用快键键win+E自动打开这个软件？
感谢分享这么详细的教程。

**Comment by violet7pan** [comment]
第一步：
[Autohotkey](https://www.autohotkey.com/download/?mt=8&uo=4&ct=appcards)
下载这个Autohotkey.安装后记得开机常驻
第二步：
在磁盘下创建一个XYplorer.ahk的文件，然后用记事本打开：复制下面一段代码保存
`#e::Run` C:\Program Files\XYplorer\XYplorer.exe ;win+e 打开XYplorer
然后双击XYplorer.ahk，它会载入Autohotkey。
试试Win+E

**Comment by violet7pan** [comment]
> 请问如何使用快键键win+E自动打开这个软件？
> 感谢分享这么详细的教程。

第一步：
[Autohotkey](https://www.autohotkey.com/download/?mt=8&uo=4&ct=appcards)
下载这个Autohotkey.安装后记得开机常驻
第二步：
在磁盘下创建一个XYplorer.ahk的文件，然后用记事本打开：复制下面一段代码保存
#e::Run C:\Program Files\XYplorer\XYplorer.exe ;win+e 打开XYplorer
其中"C:\Program Files\XYplorer\XYplorer.exe"路径换成你XYplorer的路径
然后双击XYplorer.ahk，它会载入Autohotkey。
试试Win+E
