### ISSUE TITLE
鼠标悬浮时整行高亮提示

### ISSUE THREAD

**Issue by lin-nian** [MMengyiyu/XYplorer_Help#10]
请问如何设置像原生文件资源管理器一样的鼠标悬浮, 整行亮起提示. 就是整行高亮的形式(查看方式是详细信息)

**Comment by violet7pan** [comment]
Xyploer使用的是preview（预览）功能，意味着你鼠标掠过文件夹或在其上方是预览文件。
你想要的文件提示可以通过选中文件然后Alt+Enter或者右键文件属性(properties)查看。

**Comment by Eaglewood8128** [comment]
我的问题和题主一样，如何和原生文件管理器一样鼠标悬浮后整行高亮，想实现的是我点击这一行的任意一个区域都可以进下一页【目前只能点击文件图标到名称这段区域才可进去，在文件名后的创建时间等区域双击不能进下一页】
