### ISSUE TITLE
预览markdown里面的图片显示链接路径

### ISSUE THREAD

**Issue by UIyidu9322** [MMengyiyu/XYplorer_Help#13]
大神，你好，感谢你的分享。
用XYplorer的时候预览本地的markdown文档的时候，里面的图片可以预览到吗。我的显示的是图片的本地路径。
不知道是markdown文档里面的图片不支持预览，还是XYplore需要什么插件之类的。
请问大神，这个有什么解决方法吗？谢谢哈。

**Comment by violet7pan** [comment]
QuickLook
