### ISSUE TITLE
右键空白处菜单问题

### ISSUE THREAD

**Issue by SeasonCCC** [MMengyiyu/XYplorer_Help#14]
win10 最新的windows terminal 好像没办法集成到菜单中，CEA_ListRightClickOnWhite选择3的话，windows terminal可以显示，但是会回到上一层，有办法解决吗？

**Comment by MMengyiyu** [comment]
我强烈建议集成terminal 到windows右键菜单中，然后使用集成的Windows文件管理器按钮进行跳转，然后右键开启terminal 。具体步骤在updates/tips.md
