### ISSUE TITLE
在xyplorer中右键新建文件时的问题

### ISSUE THREAD

**Issue by FOR-BANANA** [MMengyiyu/XYplorer_Help#15]
你好，在右键新建文件时发现没有offic相关的文件，需要自己手动添加后缀名才可以创建文件，请问有没有方法将它添加到右键当中去
![image](https://user-images.githubusercontent.com/47943622/72630079-8d79dd00-398c-11ea-807d-2dda05d50ce9.png)

**Comment by violet7pan** [comment]
去新建项目中，然后把office空白文件放到NewItems文件夹就可以了。
