### ISSUE TITLE
大佬可以分享一下配置文件吗，感激不尽

### ISSUE THREAD

**Issue by fengshansi** [MMengyiyu/XYplorer_Help#16]

**Comment by violet7pan** [comment]
`
[Settings]
LastTab=9
LastFileTypes=-1
ConfigLeft=7500
ConfigTop=0
ShowSpecFolderDesktop=1
ShowSpecFolderDocuments=1
ShowSpecFolderDownloads=1
ShowSpecFolderLinks=0
ShowSpecFolderUser=1
ShowFloppies=0
ShowHiddenDrives=0
ShowHiddenItems=1
ShowSystemItems=1
HideProtectedOperatingSystemFiles=0
ShowJunctions=1
ShowNethood=0
ShowRecycleBin=0
ShowPortableDevices=1
HideFoldersInList=0
; Tweak: show only available drives in Go | Drives...
PopupAvailableDrivesOnly=0
; Tweak: 
PopupVisibleSpecFoldersOnly=0
ResolveNestedJunctions=1
GFHideItems=0
GFPatternList=".*"
GFIgnoreDiacritics=0
CustomDnDMenu=1
CustomItemsCtxMenu=1
CustomItemsCtxMenuSelect=171
CustomItemsCtxMenuTreeSelect=781
CtxMenuDefaultOnly=0
GoCommandsInContextMenu=0
FindCommandsInContextMenu=0
KSInMenu=1
IDinMenu=0
AutoComplete=1
; Tweak: match from beginning (start else matching is anywhere)
AutoCompleteMatchFromBeginning=0
AutoCompletePathABar=1
AutoCompleteFilter=2
AutoCompletePathLocation=1
; Tweak: 1 = autocomplete in Address Bar includes UNC paths
AutoCompleteOnUNC=0
FindMatchCase=0
FindMatchWholeWord=0
MoveLastUsedToTop=1
DCHoverSelect=1
DCSelectionLite=0
DCSelectAllOnFocusByKey=1
DCSelectAllOnFocusByMouse=1
DCSelectAllOnItemChange=1
DCSelectMatchOnDropDown=0
; Tweak: skip icon retrieval in dropdowns
NoIconsInDropDowns=0
; Tweak: allow shell autocomplete
AllowShellAutoComplete=0
TreeExpansionIcon=1
; Tweak: min font height in pixels for large collapse/expand icons
LargePlusMinus=21
; Tweak: Tree Path Tracing width
TPTWidth=0
MainControlsBorderStyle=5
ApplyBoxColorToList=1
SetListStyleGlobally=0
VerticalGridLines=0
GridStyle=1
GridSemiTransparent=0
; Tweak: group date and size by displayed data
GridGroupByDisplay=0
UnderlineSelectedRow=0
TranslucentSelectionBox=1
TruncateMiddle=0
AdaptiveNameColumn=0
ANCMinWidth=175
ClipboardMarkersDimmed=1
ClipboardMarkersColored=1
ClipboardPreserveAfterCutPaste=0
FocusRect=0
FlatLook=1
AirPixels=0
TPTWide=0
TPTMarkNodes=0
TPTMatchWithCrumb=0
RLPMatchWithTPT=0
RLPCount=12
RememberListSettingsPerTab=1
RememberListSettingsPerTabApply=15
RenameExcludeExt=1
RenameHideExtFromBox=0
; Tweak: 
RenameNoPreselect=0
; Tweak: 
FocusNoPreselect=0
; Tweak: on Swap Names swap bases only
RenameSwapBaseOnly=0
RenameShowLength=0
ResortAfterRename=0
SerialRenameByUpDown=1
AllowMoveOnRename=1
NewItemsToEnd=0
AutoSelectAfterDeleteOrMove=0
RenameUseDialog=0
RenameAutoReplaceInvalidChars=0
; Tweak: on inline rename only
RenameAllowLeadingSpaces=0
RenameFolderSetArchiveBit=0
; Tweak: no overwrite prompt on inline rename
RenameOverwriteNoConfirm=0
RenamePreviewHideUnchanged=0
; Tweak: no prompt on opening items with overlong filenames
OpenOverlongNoConfirm=0
; Tweak: display new List contents only after all items have been retrieved and sorted
NoDisplayBeforeSort=0
PreviewRenameSpecial=0
; Tweak: natively extract embedded thumbs in PSD files
PreviewPSDEmbeddedThumb=0
; Tweak: fall back to text preview
PreviewBinariesAsTextIfNoneBetter=0
; Tweak: fall back to shell thumbnail preview
PreviewShellIfNoneBetter=1
; Tweak: keep Raw Viewed file open and locked until unselected
RawViewKeepOpen=0
QuickFileViewNonmodal=1
; Tweak: open Quick File View etc unfocused
OpenViewsUnfocused=0
NukeNoConfirm=0
NukeNoRecycle=0
NukeSkipLocked=0
NukeWipe=0
EnableColorFilters=0
ApplyColorFilterList=1
ApplyColorFilterTree=1
ColorFilterIgnoreDiacritics=1
ColorFilterShapes=0
ColorFilterColumn=0
; Tweak: e.g. FFEF00,7FFF00,FF40FF,00DFFF
SpotColorsList=
ShowMilliSeconds=0
ShowMilliSecondsPrecision=0
ShowMilliSecondsCropNulls=0
SortFoldersApart=1
SortMixedOnDates=0
SortMixedOnTags=0
SortMixedOnPaths=0
KeepFoldersOnTop=0
SortFoldersAscending=0
SortNatural=2
SortByBase=0
SortSecondaryByExactDate=0
; Tweak: 0=inherit, 1=ascending, -1=descending
SortImplicitNameOrder=0
; Tweak: e.g. a;an;the
SortLeadingWordsToIgnore=a;an;the
DefaultSortDesc=6
KeepFocusedPosAfterSort=1
ScrollToTopAfterSort=1
SortHeadersInAllViews=0
SortHeadersOffInDetailsToo=0
TAFEnabled=1
TAFUsesSortedCol=0
TAFMatchAnywhere=0
TAFIgnoreDiacritics=0
TAFHighLight=1
TAFPasteAndFind=1
TAFTimeout=750
TAFNoRepeatCharCycle=0
TAFLast=x
TAFgoLFB=0
HighlightHoveredItems=0
HighlightHoveredItemsProps=0
ShowToolTips=1
SingleClickToOpen=0
SingleClickToOpenIcon=0
PointToSelect=0
PointToSelectIcon=0
ListFullNameSelect=0
LineNumberSelection=0
DblClickGoesUp=1
MiddleClickOpensFolderInNewTab=1
MiddleClickOpensFolderInForegroundTab=0
MiddleClickOpensFileInNewTab=1
; Tweak: set to 1 to omit the Time part in the Accessed column
NoAccessedTime=0
ZuluFileTimes=0
; Tweak: set to 1 to not append Z to UTC filetimes
ZuluNoSuffix=0
AutosizeColumnsMaxWidth=0
AutosizeNameColumnRightMargin=0
; Tweak: 
AutoSizeColumnsSkips=0
SynchTreeToFind=1
ExpandOnBrowse=0
ExpandOnClick=0
ExpandLinks=0
MiniTree=1
MiniTreePaths=D:\|Desktop|Documents|Downloads|vip57|C:\|E:\|F:\|H:\
; Tweak: size of Mini Tree from Recent
MiniTreeHistoryDepth=12
MiniTreePathsFavorite=F:\|文档|Downloads|F:\CodeLibrary\STM32F429IGT6\|F:\Program Files\xyplorer_19.10.0200 (15-Aug-2018)\|G:\
MiniTreeAllowZombies=1
; Tweak: set to 1 to enable e.g. logon dialogs in MT
MiniTreeVerifyOnSelect=0
; Tweak: set to 1 to skip checking for existence/availability
TreeSkipVerifyOnSelect=0
; Tweak: set to 1 to skip network and removable drives on refresh
TreeRefreshSkipSlow=0
; Tweak: set to 1 to show icon overlay on unavailable drives
TreeOverlayUnavailable=0
; Tweak: set to 1 to suppress the horizontal scrollbar
TreeNoHoriScroll=0
TreeExpandTargetFolder=0
TreeSelectedToTop=0
AutoOptimizeTree=1
; Tweak: set to 1 to optimize the tree on each location change
AutoOptimizeTreeRadical=0
RestoreMaxiTree=0
MaxiTreePaths=
MiniTreeTopIndex=0
MaxiTreeTopIndex=0
CheckSubfoldersExist=0
CheckSubfoldersExistOnNetwork=0
TreeShowLocalizedNames=0
TreeSelectParentOfDeleted=1
TreeSelectParentOfMoved=1
ShowDragStatusBox=1
DisallowDragging=0
DisallowDraggingFromList=0
; Tweak: disallow left-dragging drives from Tree or List
DisallowDraggingDrives=0
; Tweak: 0 = System Default (Move), 1 = Copy, 2 = Move
DragOpIntraVolume=0
; Tweak: 0 = System Default (Copy), 1 = Copy, 2 = Move
DragOpCrossVolume=0
; Tweak: 
SimpleDrag=0
ConfirmDrop=0
ConfirmFileOp=0
ConfirmFileDelete=0
PortableDevicesReadOnly=0
PortableDevicesCopyByShell=1
DeleteOnKeyUp=0
DisallowDeleteByKeyTree=0
CaretPositioningLikeExplorer=0
SettingsWarnReadonly=0
FilenamesCaseSensitive=0
TouchScreenMode=0
; Tweak: icon sizes: 0 = 32x32, 1 = 48x48
TouchScreenModeProps=16
TouchToolbarZoom=1
DFCProtection=0
ClickSBToggleIP=0
StatusBarShowVersion=0
; Tweak: 
StatusBarExactBytes=1
; Tweak: 
StatusBarDeepStatus=0
; Tweak: show total bytes in Status Bar first section
StatusBar1TotalBytes=0
StatusBarFlexyWidth=1
SundayFirst=0
; Tweak: 1=Sunday ... 7=Saturday
DPFirstDayOfWeek=0
MindScrollLock=0
AgeLimitHours=
; Tweak: number of decimal places used by 'Show Age'; -1, -2 for special formats
AgeDecimalPlaces=-1
; Tweak: format: age>RRGGBB|age>RRGGBB|age>RRGGBB|...
AgeGraphicClasses=< s>6BCAA9,b2//future|<= 5 n>DCF487//up to 5 min|<= 60 n>B7DC6F//up to 60 min|d>79BB53//today|1 d>DD7BB4//yesterday|w>D0AB63//this week|m>BE7C43//this month|y>866286//this year|1 y>ABAEB4//last year|> 1 y>ABAEB4,b1//even older
AgeGraphicsAtDate=0
TimestampToleranceSecs=2
; Tweak: 
HideEmptyUserMenus=1
; Tweak: 
HideUnderscoredUDCs=0
; Tweak: format (copy, move, shortcuts, paperfolder, right-drag): RRGGBB|RRGGBB|RRGGBB|RRGGBB|RRGGBB
DragStatusClasses=5495DC|FEA311|81409C|A0A0A0|C7E6B7
; Tweak: set to 1 to detect script in AB without ::
ScriptSmartDetect=1
; Tweak: set to 1 to turn off the recursion checker
ScriptRecursionWarningOff=0
ScriptRetainPVs=0
ScriptUnindent=0
ScriptAllowMinimizeApp=0
ScriptStrictSyntax=0
; Tweak: absolute or relative to app path
ScriptsPath=
; Tweak: patch internal images with files in this path
PatchImagesPath=
; Tweak: no Click, Edit, Customize Toolbar
CTBNoRClickDefaultCommands=0
FolderSpecificSettings=1
AssumeServersExist=0
NetworkPrecheckServers=0
NetworkCapsCheck=0
SupportOverlongFilenames=1
VolumeLabelsInPaths=0
CheckServerMethod=0
CheckServer3=0
NetworkNetServerEnum=0
; Tweak: 
NetworkDriveSkipPollingBytes=0
NetworkReconnectMappedDrivesOnStartup=0
; Tweak: only effective if NetworkNetServerEnum=1
ShowAllServers=0
; Tweak: 1 = always show all hidden shares
ShowHiddenShares=0
HistoryNoDupes=0
HistoryPerTab=1
HistoryRetainsSelections=0
HistoryRetainsSortOrder=0
; Tweak: 
HistoryShowNumbersInMenu=0
; Tweak: 1 = show oldest item as number one
HistoryFirstIsOne=0
; Tweak: 1 = notify system of opened docs, 2 = of opened locations, 3 = both
AddToRecentDocs=1
AutoSelectMRUSubfolder=1
; Tweak: 
GoUpIsBack=0
CopyPathsSlashed=0
ABPathsSlashed=0
ABPathsReal=0
; Tweak: relative paths in Address Bar are resolved relative to 0=current tree path [default], 1=application path
ABRelativeToAppPath=0
ABOpenFiles=0
; Tweak: 1 =  show dropdown button on the left
ABButtonLeft=0
FavFilesDirectOpen=0
ListShowMessageOnEmpty=1
PasteToSelectedFolder=0
; Tweak: 
CreateSymlinkPrefix=""
; Tweak: 
CreateJunctionPrefix=""
CreateSymlinkPrompt=1
CreateJunctionPrompt=1
RelPath=1
FindCacheResults=1
FindCacheMaxCount=1000
; Tweak: set to 1 to level-indent search results
FindLevelIndent=0
; Tweak: set to 1 to force slightly faster mixed original sort
FindMixedSortPerLevel=0
FindFollowJunctions=0
FindNameSearchInCurrentTab=1
FindNameSearchNoRecurse=0
FindNameSearchToFindFiles=0
FindWarning=1
FindInheritColumns=1
FindNoIFilters=0
; Tweak: set to 1 to parse  !a OR b  as  !(a OR b)
FindAllowMasterInvert=0
FindNoExtendedPatternMatching=1
FindSmartBooleanQueryParsing=1
FindContentTextAllTypes=0
FindSilent=0
PaperPath=
PFAllowZombies=0
PFForcePathColumn=1
PFDeleteRemoves=1
PFWarning=1
ShowFolderSize=0
ShowFolderSizeInList=0
ShowFolderSizeInListOnNetwork=0
ShowItemCount=0
ShowFolderSizesExclude=
CacheFolderSizes=0
CacheFolderSizesMaxCount=0
CacheFolderSizesExclude=
ShowSpaceUsed=0
AutoRefresh=1
WatchNetwork=0
WatchRemovable=1
WatchDevices=1
; Tweak: auto-refresh search results
WatchFind=0
; Tweak: |-separated list of locations to watch or not to watch: -%user%\Downloads|C:\*|-N:\*
WatchIt=
WatchDuringFileOp=0
; Tweak: set to 1 to disable auto-refresh on removable drives and non-current folders
DisableSHChangeNotifyRegister=0
; Tweak: 
RefreshTreeOnTabChange=0
; Tweak: refresh the list only, not the tree, if the list is focused
RefreshListOnly=1
DimSelectedIcons=0
CacheSpecificIcons=1
GenericIcons=0
GenericIconsNetworkOnly=0
GenericIconsForAllControls=0
; Tweak: fast generic icons for net locs anywhere in the interface
GenericIconsForNetworkLocations=0
; Tweak: fast generic icons for Catalog items
GenericIconsForCatalog=0
ShowIconOverlays=0
ShowIconOverlaysOnNetwork=0
ShowLinkOverlays=1
ShowSharedFolderOverlays=1
ExtractEmbeddedIcons=0
EnableCustomFileIcons=1
; Tweak: absolute or relative to app path
IconsPath=
CustomFileAssociations=1
LinenumDigits=3
; Tweak: 1 = Tree > List, 2 = Catalog > List, 4 = Address Bar > List, 8 = Favs > List
SetFocusTo=0
; Tweak: 1 = auto-optimize, 2 = suppress overlays, 4 = resolve variables in caption
CatalogFlags=0
; Tweak: popup menus at selected control or item
PopupMenusAtSelection=1
KeyScrollMargins=0
; Tweak: increase tree node indent (in pixels)
TreeNodeIndent=0
; Tweak: tree extra white space on the left (in pixels)
TreePaddingLeft=0
TreeItemDistY=0
CatalogItemDistY=0
ListItemDistY=0
ZoomByWheel=1
WheelScrollLines=0
WheelFallbackToHorizontal=1
ListColumnExtLowerCase=0
ListHideExtInDetailsOnly=0
ListHideExtShortcutsOnly=0
; Tweak: don't scroll half-visible items into view
ListNoAutoHoriScroll=0
; Tweak: don't scroll pasted items into view
ListNoAutoScrollOnPaste=0
; Tweak: 
ListSelectOnPasteInSamePath=1
ListCheckboxSelectionMode=0
ListCellsFirstLinesOnly=0
ListAutoSelectFirst=0
; Tweak: right-padding of columns
ListDetailsColumnsSpacing=2
; Tweak: left-padding of columns
ListDetailsColumnsSpacingLeft=2
ListsLineSpacing=2
; Tweak: RRGGBB|RRGGBB (backcolor|textcolor)
ListColumnHeaderColors=
ListColumnHeaderNoBorders=0
UDCShowMenuIcons=1
UDCShowStatus=0
PFAShowFullPaths=0
PFAUseAsDefaultOpen=1
; Tweak: 
PFADefaultOpenFolders=0
; Tweak: 
PFAListOnlyExisting=0
; Tweak: 
PFAResolveLinksBeforeMatching=1
OpenAllSelectedInMultipleInstances=0
OpenManyMaxCount=0
StartPathPerm=
StartPathPermExpand=0
OpenStartPathInNewTab=1
StartPanePerm=0
AllowMultipleInstances=0
AlwaysNewInstance=0
; Tweak: set to 1 if mouse button 4 & 5 do not work
XButtonSupport=1
; Tweak: set to 1 to never start with a search
NoFindOnStartup=1
; Tweak: set to 1 to never start with a Branch View
NoBranchViewOnStartup=0
NoNetworkOnStartup=0
; Tweak: set to 1 to suppress filling the info panel on startup and tab switch
NoPropertiesStartup=0
; Tweak: set to 1 to allow start with a preview (can be slow!)
AllowPreviewOnStartup=0
StartupMinimized=0
MinimizeToTray=0
MinimizeToTrayOnXClose=0
; Tweak: set to 1 to keep the tray icon visible always
StayOnTray=0
; Tweak: set to 1 to get nagged by an 'Exit XYplorer now?' prompt.
PromptOnXClose=0
; Tweak: custom app icon
IconFile=
UseCustomCLI=0
CustomCLI=
CustomCLIArgs=
CheckForUpdates=0
CacheServers=0
PrivateHistory=0
; Tweak: 
KeepLastPaths=0
SaveMRULists=1
SavedMRULists=2047
; Tweak: one char (A-Z, 0-9) used for hotkey Win+[ ] to show app
HotKeyShowApp=
; Tweak: e.g. AB to hide drives A and B
HideDrivesByLetter=
SaveToDisk=1
SaveToDiskOptions=2159
SaveSettingsOnExit=1
NoKillTemp=0
AutoBackupConfig=1
MTNoPerformanceTip=0
ClrBackTree=16777215
ClrTextTree=0
ClrHilite=8454143
ClrBoxed=16250871
ClrTabCurrent=16777215
ClrTabOther=0
ClrTabCurrentBack=14454094
ClrTabOtherBack=15790320
ClrBtnfacePrev=15790320
ShadeInactivePane=1
ClrInactivePane=16185078
TabKeyPanes=2
PaneRubberStyle=2
AlwaysKeepFirstPane=0
; Tweak: 0=no warnings, 1=warn if pane 2, 2=warn if pane 1
SyncStandardSourcePane=0
ShowTags=1
TagColClick=0
TagColClickLabel=1
TagColClickTags=1
TagColClickComment=1
TagColClickFullRowSelect=0
TagColClickRight=1
TagColClickRightSelected=1
TagSortKeepTagsOnTop=1
TagStorage=0
TagDatCustom=
TagCopyTagsOnCopy=1
TagCopyTagsOnBackup=0
TagCopyTagsConfirm=0
TagSearchHere=0
TagsMatchAll=0
; Tweak: separator between item tags; one character only; not <>|*?
TagsSeparator=
CommentWrap=0
LabelSearchHere=0
TagStyle=1
TagsList=My Favorites, My Favorite
TagsAddNew=0
TagsFindLast=
TagsFindWildcardMatching=0
; Tweak: 0 = whole tag, 1 = any words in tag, 2 = any part of tag
TagsFindPartialMatch=0
TagsDBCheckFixedDrivesOnly=0
TagsModeOnIP=0
TagsApplyLabel=1
TagsApplyTags=1
TagsApplyComment=1
; Tweak: auto-apply changed tags in info panel
TagsAutoApply=0
TagsAutoRefresh=0
; Tweak: 0=Default, 1=ShellContextMenu
CEA_ABRightClickIcon=0
; Tweak: 0=Default, 1=Top, 2=Up, 3=Back, 4=ScrollInView, 5=Refresh, 6=Script
CEA_TreeDoubleClickOnWhite=0
CEA_TreeDoubleClickOnWhite_Script=
; Tweak: 0=Default, 1=Top, 2=Up, 3=Back, 4=ScrollInView, 5=Refresh, 6=Script
CEA_ListDoubleClickOnWhite=0
CEA_ListDoubleClickOnWhite_Script=
; Tweak: 0=Default, 1=Top, 2=Up, 3=Back, 4=ScrollInView, 5=Refresh, 6=Script
CEA_TreeMiddleClickOnWhite=0
CEA_TreeMiddleClickOnWhite_Script=
; Tweak: 0=Default, 1=Top, 2=Up, 3=Back, 4=ScrollInView, 5=Refresh, 6=Script
CEA_ListMiddleClickOnWhite=0
CEA_ListMiddleClickOnWhite_Script=
; Tweak: 0=Favs, 1=Favs Full, 2=Drives, 3=Drives+Special, 4=Tabs, 5=FavFiles, 6=Script
CEA_TreeRightClickOnWhite=0
CEA_TreeRightClickOnWhite_Script=
; Tweak: 0=Edit menu, 1=Folder's shell menu, 2=Favorites, 3=reserved, 4=Tabs, 5=FavFiles, 6=Script
CEA_ListRightClickOnWhite=0
CEA_ListRightClickOnWhite_Script=
; Tweak: 0=Default, 1=OpenInNewTab, 2=FloatingPreview, 3=FullScreenPreview, 6=Script
CEA_ListMiddleClickOnFile=0
CEA_ListMiddleClickOnFile_Script=
; Tweak: 0=Back, 1=Up
CEA_MouseBack=0
; Tweak: 0=Forward, 1=Down
CEA_MouseForward=0
FopInBackground=1
BackgroundedFileOps=7
FopAutoQueue=0
UseCustomCopy=0
UseCustomCopyForCopy=1
UseCustomCopyForMove=1
UseCustomCopyForMoveCrossVolumeOnly=0
CustomCopyDuplicateNoProgress=0
CustomMoveIntraNoProgress=1
CustomCopyDoItAlsoNextTime=0
CustomCopyFlags=0
CustomCopyNoBufferingFromBytes=0
CustomCopyNoDoEvents=0
; Tweak: no log is created if this or more files
CustomCopyNoLog=0
Copier=
CopierLast=
CopierList=
BJHideCompleted=0
; Tweak: allow backgrounding drops from outside
BJAllowDropFromOutside=0
; Tweak: time (in ms) between consecutive background jobs
MsecDelayNextQueuedJob=0
BJSoundAllDone=
BJSoundAllDuration=0
BJSoundJobDone=
BJSoundJobDuration=0
FileOpProgressModeless=1
NoDeleteConfirmation=0
PreservePermissionsOnMove=1
; Tweak: 0 = ask, 1 = always, 2 = never
AutoRichFileOps=0
; Tweak: turn off safety check on move up
NoCheckMoveUp=0
RepOFCur=0
RepOFDate=0
RepOFAppend=0
RepLFOnOversized=0
RepCSVSepOpt=0
RepCSVSepOther=,
BackupOnNameCollision=0
BackupOnNameCollisionAsk=0
BackupOnFailure=0
BackupOnFailureAsk=0
BackupOnScarceSpace=-1
BackupRenameFoldersOnCollision=0
BackupAskBeforeMergingFolders=0
BackupAskOnReadonly=0
BackupRemoveReadonly=0
BackupPreserveItemDates=1
BackupShowProgress=1
BackupKeepProgressOpen=1
BackupLogging=0
BackupLogToDefaultLocation=1
BackupLog=<xydata>\Log\Backup_<date yyyy-mm-dd_hh-nn-ss>.txt
BackupPopStats=0
BackupSkipJunctions=1
BackupSafeOverwrite=1
BackupVerify=0
BackupSkipVerificationOnHDs=1
SyncCopyItems=1
SyncOnNameCollision=-1
SyncDeleteUniquesInTarget=7
PreviewDelayMsecs=0
ShowImageInfos=1
ShowTextInfos=1
ShowRawViewInfos=1
Tail=0
Zoom=0
Bord=3
HighQualityImageResampling=1
HighQualityImageResamplingInterpolationMode=0
; Tweak: e.g. 2 = low quality on >= 2x zoom
LowQualityImageResamplingOnZoom=0
AutoRotate=1
Grid=0
GridColor1=16777215
GridColor2=14540253
; Tweak: max area of previewed images, 0 = unlimited
PreviewMaxArea=0
LoopMedia=0
AutoPlay=1
PlayFirstSecs=0
CountFirstSecs=3
KeepPlayingOnPanelDown=0
AudioPreviewWithPanelDown=0
; Tweak: use native audio preview in PP
AudioPreviewPPNative=0
; Tweak: if fast methods fail fall back to slower methods
AudioPropsSecondTries=0
PreviewStaticFrame=0
SkipIntroMilliSeconds=0
ShrinkToFit=0
ShrinkToFitWidth=0
ShrinkToFitAllowPanning=0
MDBUFullScreen=1
MDBUBorder=0
MDBUCentered=0
MDBUonIcons=0
MDBUaudio=0
MDBUaudioLoop=0
MDBUBmovement=0
MDBUAllowDragByThumb=0
MUSDFolderContentsPreview=0
MUSDleft=0
MUSDright=0
MUSDtree=0
MUSDlist=1
FullZoom=0
FullName=1
FullTopAlignCropped=0
FullMDBU=1
FullBackground=1
FullLockZoom=0
FullLockZoomPosition=0
FPSnap=0
FPLeft=484
FPTop=157
FPWidth=1000
FPHeight=750
FPWindowState=1
FPFit=0
FPColorLightGray=777777,CCCCCC
FPEnableCKS=0
FPCyclicNavigation=0
FPNavigateByClick=0
FPNavigateByGroup=1
FPWhiteBorder=1
FPWhiteBorderPixels=0
FPWhiteBorderPercent=7
FPWhiteBorderShadow=1
FPPhotoData=1
FPHistogram=0
FPHistogramOriginal=0
FPHistogramType=0
FPInvert=0
FPGrayscale=0
FPZoomPosX=0
FPZoomPosY=0
FPZoom=0
FPZoomOrig=0
FPShowTags=0
FPShowScriptButton=0
FPScript=""
ShellPreviewMaxWidth=0
ShellPreviewMaxHeight=0
ShellPreviewPdfMaxWidth=0
ShellPreviewPdfMaxHeight=0
FontSample=
FontSampleSize=0
EnSrvMap=0
MapFrom=
MapTo=http://localhost/
; Tweak: show HTML doc title in preview
ShowWebPreviewInfoBars=0
HTMLShowTitle=0
TPWrap=0
TextPreviewCodePage=0
TextPreviewCodePageRemember=0
; Tweak: e.g.: IBM 437 (DOS-US)=437;IBM 850 (DOS-Latin-1)=850; ...
UserCodePages=
ReplaceTabsBySpaces=0
CheckForBOMlessUTF8=1
MaxBytesTextPreview=5242880
DisableMediaPreviewShortcuts=0
PreviewTexts=1
PreviewOffice=1
PreviewWeb=1
PreviewFonts=1
PreviewImages=1
PreviewAudio=0
PreviewVideo=0
PreviewAsThumbnail=1
PreviewUDPH=1
NoPrevImages=
NoPrevAudio=
NoPrevVideo=
NoPrevUDPH=
NoPrevOffice=
NoPrevWeb=
NoPrevText=.htm.html.mht.mhtm.mhtml.msg.
NoPrevFont=
NoPrevPreviewAsThumbnail=
; Tweak: exclude file types from Raw View
NoPrevRaw=
; Tweak: add (bim, bum)/remove (bam) extensions to/from factory defaults: bim.-bam.bum
TextPreviewCustomExtensions=.
TextUTF8CheckCustomExtensions=
FontPreviewCustomExtensions=.
ImagePreviewCustomExtensions=.
OfficePreviewCustomExtensions=.
WebPreviewCustomExtensions=.
AudioPreviewCustomExtensions=.
VideoPreviewCustomExtensions=.
PreviewAsThumbnailExtensions=.
UserDefinedPreviewHandlers=.
VectorPreviewCustomExtensions=
ArchivePreviewCustomExtensions=
ZipFldrCustomExtensions=
ZipViewCustomExtensions=
ZipPathUnRAR=%ProgramW6432%\WinRAR\UnRAR.exe
ZipPath7zip=%ProgramW6432%\7-Zip\7z.exe
ExePreviewCustomExtensions=
SpecificIconsCustom=
ThumbFromIconCustom=
IFilterCustom=
ClosePreviewBeforeRename=
DropTargetCustomExtensions=
AudioMCICustomExtensions=
; Tweak: fallback to this handler if no other handler was registered for this filetype
CustomPreviewHandlerFallback=
InputShowTipsByDefault=0
; Tweak: default start location for a new tab
StartPathNewTab=
NewTabPosition=0
ActivateTabOnClosingCurrent=0
TabCycleMRU=0
TabWheel=1
MaxNumTabs=0
TabAutoSelect=1
TabAutoSelectInactivePane=0
DelaySelectHoveredTab=1000
TabHiliteSelOnInactivePane=0
TabWidthMax=250
TabWidthMin=0
TabHeightAdd=0
TabUseCustomColors=1
TabUseCustomColorsIncludePlus=0
TabMatchSelectedWithCrumb=0
TabMatchSelectedWithCrumbPrio=0
TabIPUseCustomColors=0
TabIcons=1
TabSelBold=1
FlexyTabs=1
TabShowPlusButton=1
TabShowListButton=1
; Tweak: 0 = flexible, 1 = left, 2 = right
TabShowListButtonPos=0
TabPromptOnCloseLocked=0
TabCapDisplay=0
TabCapCustom=<drive>: <folder>
TabXClose=1
TabOnDblClick=5
TabOnMiddleClick=0
TabVisualStyle=0
; Tweak: IP tabs: 0 = shadow style, 1 = classic style, 2 = flat style, 3 = flat style with lines
TabIPVisualStyle=3
TabYellow=0
; Tweak: 
TabsetsNoPaneActivation=1
AutoSaveTabsets=0
TabsetsCanRevertAcrossSessions=1
GoHomeRestoresListLayout=0
ShellScope=1
; Tweak: BEWARE: makes parts of the Control Panel unusable
ShellIncludeSpecialFolders=0
; Tweak: store paths relative to app path: 1 = on removable drives, 2 = on any drive, 4 = relative to app drive
PortableTabs=0
; Tweak: autoselect first tab with a matching locked homezone when current tab is locked
TabBinding=0
TabReuseTabs=0
; Tweak: reuse existing tabs when changing locations in whichever way
TabReuseTabsRadical=0
; Tweak: RRGGBB
TabBarBackColor=
CrumbVisualStyle=1
CrumbPathStyle=0
CrumbFontMilliSize=10000
CrumbBold=1
CrumbNav=0
CrumbHamburgerShow=1
CrumbHamburger=:dpmoveto|:dpcopyto|-|:newfolder|:copypath|-|:pp
CrumbIcon=1
CrumbDriveLabels=1
CrumbDown=1
CrumbCheckSubs=1
CrumbDropdownStyle=2
CrumbShowBorder=0
CrumbHeightAdd=0
clrCrumb1ActiveBack=14454094
clrCrumb1ActiveText=16777215
clrCrumb1InactiveBack=12367281
clrCrumb1InactiveText=16777215
clrCrumb2ActiveBack=4616373
clrCrumb2ActiveText=16777215
clrCrumb2InactiveBack=11646136
clrCrumb2InactiveText=16777215
`
选自部分.ini，我没办法全部提供，可能会导致许可证到期。
