### ISSUE TITLE
XYplorer预览、主文件夹的设置问题

### ISSUE THREAD

**Issue by yoghurtdewdew** [MMengyiyu/XYplorer_Help#18]
大佬你好！有幸拜读教程，在下有几个使用方面的问题，渴望得到解答指导：
（1）XYplorer可以预览文件，但是对pdf和视频文件不能很好的解码，有的文件能够预览，有的文件则不能够。对于文本文件（比如说word文档）预览出来也会有乱码的情况。针对XYplorer预览不能解码的情况可否有其他办法解决？比如说给XYplorer添加/配置一个解码器来辅助预览文件？
（2）之前用过Clover来替代默认的资源管理器，但是时间比较久了，Clover的设置里也没有取消替代资源管理器的选项，目前打开XYplorer作为默认资源管理器选项时，win+E仍然是clover。
（3）对于预览问题，用quicklook可以实现空格键预览，在clover里可实现预览图片、pdf等文档、音视频等各种文件，在XYplorer中无法使用空格键来调用quicklook，即使在XYplorer中未定义空格键作为快捷键，那么如何实现在XYplorer中通过快捷键调用quicklook来预览文件呢？
（4）在对XYplorer进行自定义工具栏时，看到除了纸文件夹以外，还有主文件夹，纸文件夹大佬讲的特别比较清楚了，但是主文件夹过了这么久我还是不会用，恳请得到指导。
以上便是我的问题，希望得到指点，谢谢！

**Comment by violet7pan** [comment]
部分解答我放在updates/tips.md

**Comment by yoghurtdewdew** [comment]
谢谢大佬！非常完美的解答了问题（3）🥰
暂时忽略问题（2）
现在对于上述问题（1）（4）还是想要求解下
另外，又多了一个问题（5）：updates/tip.md中好像说了如何将xyplorer集成到everything的右键菜单，不过我的需求其实是如何将everything集成到xyplorer的右键菜单 来实现快速在指定路径内（xyplorer中打开的文件夹下）进行文件搜索，不知道这个可否通过创建脚本来实现呢
谢谢！

**Comment by violet7pan** [comment]
xyplorer空白处右键应该是没办法修改的，xyplorer对文件右键能不能修改我还不知道。所以走Xyplorer进行右键添加应该是行不通的（我猜测）。不过我的方法是绑定快捷键运行脚本文件，通过脚本调用everything。
[演示图](https://s1.ax1x.com/2020/11/04/Bc3yyd.gif)
我看看有空发到tips.md

**Comment by chenxin0397** [comment]
** 关于升级**，每次升级导入ini文件都会丢失原来的文件标签和备注信息，请问是不是我不知道如何保存相关文件？

**Comment by violet7pan** [comment]
> ** 关于升级**，每次升级导入ini文件都会丢失原来的文件标签和备注信息，请问是不是我不知道如何保存相关文件？

备份和还原的问题更新到tips.md了

**Comment by codeshif** [comment]
也没说咋解决的啊，我的天，我看tips里面也没有这个 @violet7pan
