### ISSUE TITLE
关于xyplorer与quicklook空格键冲突

### ISSUE THREAD

**Issue by forai** [MMengyiyu/XYplorer_Help#19]
在xyplorer界面内，使用空格键不能实现quicklook软件的预览功能，请问楼主知道怎么解决吗？
谢谢。

**Comment by violet7pan** [comment]
空格作为保留键，即XYplorer预留了空格，所以你不能再XYplorer中使用空格，quickLook的使用可以参考我的tips.md

**Comment by chenxin0397** [comment]
** 关于升级**，每次升级导入ini文件都会丢失原来的文件标签和备注信息，请问是不是我不知道如何保存相关文件？
