### ISSUE TITLE
适配listary快速切换

### ISSUE THREAD

**Issue by JM-LIN** [MMengyiyu/XYplorer_Help#2]
楼主，我的listary是正版，可是结合xyplorer就是不能使用快速切换功能，你的可以吗？感谢楼主！！！

**Comment by violet7pan** [comment]
可以啊，首先，
【1】listary设置->应用程序设置，添加XYPLORER的目录导入。
【2】你必须打开文件对话框，这个对话框右下角的按钮叫做“打开”，而不是“确定”。
【3】打开XYPLORER需要的文件目录<a>
【4】切换到文件对话框
【5】文件对话框：切换到文件目录<a>
