### ISSUE TITLE
关于xyplorer升级之后的注标和备份

### ISSUE THREAD

**Issue by chenxin0397** [MMengyiyu/XYplorer_Help#21]
大佬，为什么我替换成新的版本之后，所有在上一个版本中标注过或备注过的信息全部没有了呢？是不是这些也需要保存到某个文件里再导入？

**Comment by violet7pan** [comment]
XYplorer/Data/下是否有tag.dat。如果tag.dat大小为0，证明标注tag数据都没了，可能找不回了。如果你在设置中开启自动备份，可以看看XYplorer/Data/AutoBackup/下有没有tag.dat，若文件大小不为0，可以复制到XYplorer/Data/目录下，然后tags->import local tags。以后切记要备份Data文件夹哦

**Comment by violet7pan** [comment]
如果用替换升级，在下载新版本替换旧版本之前，把旧版本的Data文件夹保存起来，替换后才可以还原回去。否则，你的用户数据都会被覆盖。因此，我建议你从XYplorer菜单栏Help->Online Supprot->Check for Updates进行在线更新，这样不会丢失用户数据。
如果你仔细观察你下载新版本的话，可以发现它目录下Data的*.dat和*.ini都不是你原来使用的。而这些都应该是用户之间长期使用时留下来的用户数据。

**Comment by chenxin0397** [comment]
我可否每次升级时，不替换data文件夹？

**Comment by violet7pan** [comment]
在线升级的方式就不用替换data。但是如果是Crack版，在线升级可能面临许可证到期的风险。

**Comment by violet7pan** [comment]
你可以看看tips.md我更新了这部分的情况
