### ISSUE TITLE
关于详细列表的提问

### ISSUE THREAD

**Issue by chenxin0397** [MMengyiyu/XYplorer_Help#22]
在 某文件**属性** 的 **详细信息** 里 作过**标记**的文件，其标记内容有没有可能通过xyplorer的详细列表显示出来？我感觉xyplorer是另一套标记和备注的方式，是不是不能共同windows对文件的标记信息？

**Comment by violet7pan** [comment]
打开Tag列表，效果：
[![D1RSr4.png](https://s3.ax1x.com/2020/11/21/D1RSr4.png)](https://imgchr.com/i/D1RSr4)
方法：
[![D1RERK.md.png](https://s3.ax1x.com/2020/11/21/D1RERK.md.png)](https://imgchr.com/i/D1RERK)

**Comment by chenxin0397** [comment]
[![rVV9Y9.png](https://s3.ax1x.com/2020/12/12/rVV9Y9.png)](https://imgchr.com/i/rVV9Y9)
https://imgchr.com/i/rVV9Y9
其实我是这个意思，文档属性里的“标记”在Explorer里能显示，但在Xyplorer里不知道是否也可以。
https://s3.ax1x.com/2020/12/12/rVVbAe.png
另外，xyplorer是否能显示音频文件的时间长度？

**Comment by violet7pan** [comment]
第一个问题：使用property函数,通过该函数读取这个文档的属性"标记"的值，具体在XYplorer.chm有介绍，里面有附一个Microsoft Doc，去里面查看该属性名进行Scripting编写，然后整合到Custom Column去就可以了。
`::rtfm "idh_scripting_comref.htm#idh_sc_property";	//property()`
第二个问题：
有的,添加Custom Column，找到"Length, Special Property (wav;ogg;flac;mp3)"进行添加。
这些在我Tips.md都有讲解的。

**Comment by chenxin0397** [comment]
第二个问题已经处理了，第一个问题对我来说比较深奥，有没有图文教程？
如果升级，若要保留这些设置，是不是data文件夹不能被替换更新？
我不会写Scripting，而且没有梯子，大部分图都被墙了😭😭😭
我想我最多只能做到这一步：https://imgchr.com/i/rZGbng
[![rZGbng.png](https://s3.ax1x.com/2020/12/12/rZGbng.png)](https://imgchr.com/i/rZGbng)

**Comment by chenxin0397** [comment]
我不会写Scripting，而且没有梯子，大部分图都被墙了😭😭😭

**Comment by violet7pan** [comment]
我的markdown没办法看吗，你注册"码云"，然后在码云中新建一个仓库，在创建附近有个“导入”按钮，把我这个链接复制过去，你就可以在码云中国中观看我的项目，我在这一部分写得很清楚，叫“自定义列”和“定制文件列表”。如果你不懂，你先百度搜“码云克隆GitHub”

**Comment by chenxin0397** [comment]
可是我怎么才能够写合适的代码写进去呢？ 刚才借了个梯子，发现全是英文界面，好在我蒙对了几步。真心看不懂

**Comment by MMengyiyu** [comment]
把你的QQ发到violet7pan@outlook.com

**Comment by chenxin0397** [comment]
发了

**Comment by MMengyiyu** [comment]
> 
> 
> 发了

你直接发到这里吧，收不到。发了过会你再删Q

**Comment by chenxin0397** [comment]
> > 发了
> 
> 你直接发到这里吧，收不到。发了过会你再删Q

7424863
