### ISSUE TITLE
关于右键新建文件

### ISSUE THREAD

**Issue by helcc** [MMengyiyu/XYplorer_Help#25]
你好，有个问题咨询下。习惯右键新建文件，比如docx，excle，emmx等文件，这些文件在win10提供的右键菜单中可以方便使用，但XYPloer右键只能自己输入文件名加后缀，如何能做到跟WIN10右键新建菜单一样的功能呢？

**Comment by violet7pan** [comment]
https://imgchr.com/i/yUzT2j
在图片XY路径中方框路径下创建即可。
XYplorer\Data\NewItems目录下创建你要的文件模板，因为右键空白处，弹出的菜单中NewItem会有这些模板，而且你还可以对每个模板定制，比Window10创建一个空白内容的后缀要强得多。

**Comment by helcc** [comment]
thank you
