### ISSUE TITLE
大佬怎么在xyplorer使用teracopy?

### ISSUE THREAD

**Issue by DLGum** [MMengyiyu/XYplorer_Help#26]
如题。
我是用注册机直接破解了官网最新版。
发现悬停自动预览没生效。
以及不知道怎么使用teracopy。

另外跳转好像有问题。
比如浏览器打开某文件下载目录，win自带跳转后会自动滚动到相应位置选定对应文件。
xyplorer跳转后只是打开了下载目录。东西要自己翻。

**Comment by violet7pan** [comment]
我也没用过teracopy，你在XYplorer使用文档中搜索teracopy就会出现一个teracopy integration的使用方法。或者地址栏输入
rtfm "idh_settings.htm#idh_settingsexternalcopyhandlers";
跳转并焦点到目标文件这是因为浏览器都实现了对Explorer的焦点，但XY设置为默认文件管理器，没有实现这个功能，不建议XY设置为默认文件管理器。我在贴文中有提及过。
如果你想要跳转到对应文件，XY提供了"/select"外部命令行参数，除非浏览器在调用时能加入这个命令行参数，不然没办法焦点到目标文件
