### ISSUE TITLE
标签设置中，“在拖过时自动选择标签”选项的实际作用为何？

### ISSUE THREAD

**Issue by Cidenia** [MMengyiyu/XYplorer_Help#27]
大佬你好，有两个问题想请教一下。

1. 结合Listary使用时，用原生资源管理器打开文件所在文件夹时，会自动焦点到目标文件，XYplorer只能打开所在文件夹而不会显示文件具体位置，父文件夹文件少时可以手动查找，文件多时比较麻烦。请问这个可以实现跟原生一样的效果吗？

2. 可否指点一下这三个选项实际的作用是什么，我怎么试都没发现实际影响了什么操作……

![](https://ftp.bmp.ovh/imgs/2021/03/251617af1bec8ebd.jpg)

**Comment by violet7pan** [comment]
### 问题1
Listary可以自动焦点到目标文件，这是因为Windows的Explorer提供了[接口](https://docs.microsoft.com/en-us/windows/win32/shell/developing-with-windows-explorer)，而Listary利用这些接口实现了“寻找时自动焦点选中文件”的功能。
Listary没有实现在XY实现自动焦点文件的功能，这可能是因为XY提供给用户的编程方式只有Scripting。
[https://violet7pan.github.io/posts/c07fdd8a/](https://violet7pan.github.io/posts/c07fdd8a/)中的2.5
### 问题2
在拖过时自动选择标签为Auto-select tabs on drag-over，实际上应该译为“鼠标拖拽时自动切换标签页”。
如果你在标签页A中拖拽一个文件A不放，将拖拽的鼠标放在非活动标签页B上，在鼠标拖拽不放300ms后，会切换到标签页B。
