### ISSUE TITLE
请问xyplorer19版本中展平文件夹的功能取消了吗？

### ISSUE THREAD

**Issue by ddkk3000** [MMengyiyu/XYplorer_Help#28]
就是将同一文件夹下的多个分文件夹的文件全部到同一个目录中。我记得原来有这个功能。现在找不到了（我记得是鼠标右键菜单的功能）。希望大佬能教导一下。

**Comment by violet7pan** [comment]
打开你所述的多个子文件所在的文件夹，在工具栏按下Branch View即可。
Branch View可以通过右键工具栏添加

**Comment by ddkk3000** [comment]
但是，这种查看模式，无法实际操作呀

--------------原始邮件--------------
发件人："violet7pan ***@***.***&gt;;
发送时间：2021年4月10日(星期六) 上午9:56
收件人："violet7pan/XYplorer_Help" ***@***.***&gt;;
抄送："ddkk3000 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [violet7pan/XYplorer_Help] 请问xyplorer19版本中展平文件夹的功能取消了吗？ (#28)
-----------------------------------

 

 
打开你所述的多个子文件所在的文件夹，在工具栏按下Branch View即可。
 Branch View可以通过右键工具栏添加

**Comment by violet7pan** [comment]
Branch View就已经将子目录的文件显示集中在一个目录显示了，你选中这些文件右键不就能操作了吗，基本的复制剪切删除重命名都有，再次按下Branch View就退出分支视图，你再粘贴到目录不就好了。

**Comment by ddkk3000** [comment]
无法选中呀。您能给录个gif吗

--------------原始邮件--------------
发件人："violet7pan ***@***.***&gt;;
发送时间：2021年4月10日(星期六) 下午2:15
收件人："violet7pan/XYplorer_Help" ***@***.***&gt;;
抄送："ddkk3000 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [violet7pan/XYplorer_Help] 请问xyplorer19版本中展平文件夹的功能取消了吗？ (#28)
-----------------------------------

 

 
Branch View就已经将子目录的文件显示集中在一个目录显示了，你选中这些文件右键不就能操作了，基本的复制剪切删除重命名都有，再次按下Branch View就退出分支视图，你再粘贴到目录不就好了。

**Comment by violet7pan** [comment]
![branchview.gif](https://i.loli.net/2021/04/10/KtlnjZTi9Q6Y125.gif)

**Comment by ddkk3000** [comment]
谢谢，我尝试一下。

--------------原始邮件--------------
发件人："violet7pan ***@***.***&gt;;
发送时间：2021年4月10日(星期六) 下午2:22
收件人："violet7pan/XYplorer_Help" ***@***.***&gt;;
抄送："ddkk3000 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [violet7pan/XYplorer_Help] 请问xyplorer19版本中展平文件夹的功能取消了吗？ (#28)
-----------------------------------
