### ISSUE TITLE
请问如何解决文件夹重命名中文乱码的问题

### ISSUE THREAD

**Issue by shootheart** [MMengyiyu/XYplorer_Help#29]
文件夹重命名（或新建文件夹）时，输入中文会显示为问号。xyplore已更新。
查了下网上较多的解决方法，是将win10输入法中的“美式键盘”删除，但是实测没有解决

系统：win10 家庭版 1909
软件版本：21.70

**Comment by bgzo** [comment]
21.90 我这没啥问题
win10 专业版

**Comment by violet7pan** [comment]
Windows打开设置，在搜索框中输入“设置区域格式”，保证当前格式为**中文(简体，中国)**。
前往[Chinese (Simplified) 简体中文 - XYplorer Beta Club](https://www.xyplorer.com/xyfc/viewtopic.php?f=12&t=9155)下载.lng的语言文件，如果你能科学浏览该论坛，请下载该帖子最新回复的附件**ATTACHMENTS**。
