### ISSUE TITLE
默认打开浏览器问题

### ISSUE THREAD

**Issue by guqinglei123** [MMengyiyu/XYplorer_Help#3]
我使用bandizip解压之后，会自动打开浏览器。这个浏览器会是官方的默认浏览器，我想请问问一下有没有办法设置为xyplorer

**Comment by violet7pan** [comment]
你解压了什么，需要用XYPLORER打开？具体到什么格式的文件。是HTML格式或者图片还是PDF还是TIFF还是别的什么，具体的文件格式要调用其他程序打开可以在工具->自定义文件格式 里面设置
