### ISSUE TITLE
虽然不建议，但是还是想接替默认文件管理器

### ISSUE THREAD

**Issue by yefenghu** [MMengyiyu/XYplorer_Help#30]
找了N多文件管理器，没一个第三方能完美替代默认资源管理器的，不知道是我方式不对还是怎样。
目前的思路是使用增强默认资源管理器，用过clover+QTTBABR、百叶窗+QTTABAR、extab+QTTABAR感觉都有各自的问题，最终只保留了百叶窗。想咨询下大佬，有什么推荐。终极目的就是多标签，不要有割裂。

**Comment by violet7pan** [comment]
Windows文件管理器（Explorer）集合许多Windows核心组件，可用于磁盘读取，写入文件之类的操作，第三方文件管理器做不到真正代替它，第三方也是间接调用。
可以通过XY中设置作为默认文件管理区，但注册表修改的只是部分应用调用行为改为XY调用，但无法做到真正修改。
而且也做不到完全取代Explorer，在EULA（最终用户许可协议）应该是不允许的，违法的。开发者想来没办法开发出完全替代Explorer。
如果你那么喜欢多标签，增强Explorer最稳定的方法是使用stardock groupy。
