### ISSUE TITLE
Quick file view 不能正常显示

### ISSUE THREAD

**Issue by huauh** [MMengyiyu/XYplorer_Help#32]
您好，抱歉麻烦到您，您看是否可以帮忙看看，这个怎么解决：目的就是，想要使用Ctrl+Q预览图片或PDF时，也能正常显示出来：
List中的图片和PDF，在使用 F11 或 Ctrl+F11 预览时，都可以正常显示（如图1），但若使用Ctrl+Q（Quick file view）时，就不正常显示了，而总是显示为二进制一样的代码（如图2）。
![image](https://user-images.githubusercontent.com/21192376/139517101-4921b4d1-3531-4d5e-adf8-a33d44c93585.png)

![image](https://user-images.githubusercontent.com/21192376/139517124-dc0018e9-3ef5-4763-b531-ef332b1fdf8e.png)

**Comment by violet7pan** [comment]
Quick File View的功能是这样的：
- 二进制文件（即非文本文件）会以十六进制形式显示。
- 非二进制文件（如文本文件）会以文本形式显示。
- 只有前256KB大小的内容会显示到Quick File View窗口

例如：
图像，PDF当然是二进制文件，所以会以十六进制形式显示代码在内存的地址，该地址的数据内容，数据预览。
如果是包含中英文的.txt文件，用Quick File View可以正常查看。
Quick File View是hard-code的，因此不用想着用这个来达到你想要的预览效果。

可使用替代软件[QuickLook](https://github.com/QL-Win/QuickLook/releases)，然后利用XY菜单栏User-Defiend Commands绑定一个快捷键用于调用启动QuickLook的脚本
RunQuickLook.xys
```
	// 当前选中项目不为空
	if (<curitem> != "") {
		run "<xypath>\..\QuickLook\QuickLook.exe" "<curitem>";
	}
```
`<xypath>\..\QuickLook\QuickLook.exe`替换为QuickLook.exe的路径
该脚本存放路径为<xyscripts>，通过地址栏输入可进入该目录。
在User-Defiend Commands窗口的左侧选择Load Script File
1. 输入Caption为QuickLook
2. Script File为<xyscripts>\RunQuickLook.xys
3. 绑定快捷键，可绑定为<kbd>Alt + Q</kbd>
4. 选中文件，使用快捷键即可完成预览
![image](https://user-images.githubusercontent.com/42297475/139587985-00c65c4a-7916-4117-941b-2c5f9ba938fd.png)

**Comment by huauh** [comment]
非常感谢您的详细解答！已按照您介绍的方法设置好，解决了我的问题！
