### ISSUE TITLE
博主企鹅号多少

### ISSUE THREAD

**Issue by phoenixchl** [MMengyiyu/XYplorer_Help#33]
博主企鹅号多少呢，望回复，个人用xy很多年了经验很丰富，可互通有无~

**Comment by phoenixchl** [comment]
> 博主企鹅号多少呢，望回复，个人用xy很多年了经验很丰富，可互通有无~

 Listary5 Pro可以完美集成到xy，不需要6的哈~

**Comment by OxYancy** [comment]
问下 怎么打开窗口默认是 平铺视图呢  或者有没有好的视图推荐
