### ISSUE TITLE
打开挂载的cloudDrive 很卡

### ISSUE THREAD

**Issue by OxYancy** [MMengyiyu/XYplorer_Help#34]
打开挂载的cloudDrive 很卡

**Comment by violet7pan** [comment]
以前我使用过映射为网络硬盘的坚果云，可以挂载成硬盘是好事，但浏览时，只要是文件夹中的文件多，这样就需要在线读取文件列表，如果没有缓存到本地，每次读取都会卡顿。当缓存好了，重新进入目录就不会卡顿了。CloudDrive也应该就是这样的。这是这种浏览方式的问题，不是XY的问题。
我下载了CloudDrive试用了一下，确实是这样的。
