### ISSUE TITLE
迅雷和everything等软件打开文件所在位置时如何定位文件

### ISSUE THREAD

**Issue by ticgac** [MMengyiyu/XYplorer_Help#5]
迅雷和everything等软件右键打开文件位置或者打开路径后，xyplore只是单纯的打开了文件所在的目录，如何向自带管理器一样打开目录同时选中了打开的文件？另外标签栏右键“设为默认标签栏”的作用是什么？没明白这个设置！

**Comment by violet7pan** [comment]
你可以在Help菜单栏找到Content and Index，里面可以查询关键字Default tab.
  这个默认标签栏具体的作用是：比如你对一个Tab（Tab名字叫做F:\Documents）设置了Default tab，那么你在迅雷下载过的A文件时（F:\下载库\A.txt）右键打开文件夹时，新打开的Tab是在这个Default tab上打开的。因此，这个Tab会从F:\Documents -> F:\下载库。目的是为了减少新Tab的数量。迅雷打开Tab属于被动打开，因此会代替这个默认Tab。
  具体选中文件的问题，你可以在打开的XYplorer的目录下使用Live filter box快速查找文件(Alt + F3)，在这个box搜索关键字找到文件，不用选中是因为迅雷为对XYplorer作优化或者XYplorer为对迅雷作优化。
