### ISSUE TITLE
这几天也在用这个，发现一个问题不知能不能解决

### ISSUE THREAD

**Issue by itheabyss** [MMengyiyu/XYplorer_Help#6]
如果在配置里设置了始终显示文件夹大小，这个每次打开文件夹多的目录会很卡。而我以前用的Q-Dir去不会，为了这个问题很头疼，刚刚又试了xplorer2，同样设置显示文件夹大小，反应非常快，甚至比Q-Dir还快，再多的子目录都感受不到延迟。

也就是说我这三个工具，都有显示文件夹大小的功能，xyplorer是最弱的一个，不知有没什么办法改善？

**Comment by webmasterxp** [comment]
Hello，你好，我也在用xyplorer，觉得很不错，就是不知道能不能显示Windows的库文件夹？

**Comment by violet7pan** [comment]
建议移步：https://www.xyplorer.com/xyfc/viewtopic.php?t=19296
链接解决的是修改custom columns后的folder打开变慢。
我目前只找到这种问题的解决
