### ISSUE TITLE
如何在XYPlorer中显示Windows的库文件夹

### ISSUE THREAD

**Issue by webmasterxp** [MMengyiyu/XYplorer_Help#7]
Hello，你好，我也在用xyplorer，觉得很不错，就是不知道能不能显示Windows的库文件夹？

**Comment by violet7pan** [comment]
1：下载附件（在官网论坛的Show_Libraries_v1.1.1.zip）
https://www.xyplorer.com/xyfc/viewtopic.php?f=7&t=11421

2：Cmd到附件解压路径
3：https://imgchr.com/i/ZGJ0Cq
