### ISSUE TITLE
我按照楼主设置后关闭了一下

### ISSUE THREAD

**Issue by MybeautifulSunShine** [MMengyiyu/XYplorer_Help#8]
我按照楼主设置后关闭了一下,TMD(哭)费了一个小时跟着设置的,怎么全部由恢复了默认设置好尴尬,我用的是19.10版本的,楼主有木有好的办法,启动一次设置一次也不是事儿啊,,,,,

**Comment by lioilLRM** [comment]
试试设置完成后，在菜单栏的File--> Restart withoud Saving 。
重启保存看行不。
