### ISSUE TITLE
如果我设置了git怎么让它右键进去

### ISSUE THREAD

**Issue by MybeautifulSunShine** [MMengyiyu/XYplorer_Help#9]

**Comment by lioilLRM** [comment]
老哥，我来回答你的问题.
本来我搜索没有思路的，但是根据你的问题获得关键词 git,便 google 搜索了一下，终于搞定了！
根据搜索结果搜索到：https://www.xyplorer.com/xyfc/viewtopic.php?t=16043
然后按照论坛的回答，看到了官方的答案：https://www.xyplorer.com/faq-topic.php?id=tweak
在根据知乎的搜索答案：https://www.zhihu.com/question/59732564
综合了一下答案配置xyplorer.ini文件，就搞定了。
步骤如下：
1.菜单栏：Tools-->open Configuration File 打开 xyplorer.ini 配置文件。
2.通过查找:CEA_ListRightClickOnWhite 关键字，将其值设置为：1 
如下：CEA_ListRightClickOnWhite=1
其他默认配置：
Tweak: 0=Edit menu, 1=Folder's shell menu, 2=Favorites, 3=reserved, 4=Tabs, 5=FavFiles, 6=Script

3.保存 xyplorer.ini 文件。
4.菜单栏：File-->Restart without Saving 重启后就可以了。
5.最终结果图：上传不了图片。。

**Comment by MybeautifulSunShine** [comment]
感谢老哥一起进步
